# original code taken from https://medium.com/thelorry-product-tech-data/amazon-ec2-deployment-complete-ci-cd-pipeline-using-github-actions-and-aws-codedeploy-8a477123ff7e#:~:text=GitHub%20Actions%20will%20take%20place,to%20do%20the%20deployment%20part.
name: CI/CD Pipeline
on:
  push:
    branches: [main, 'feature/deploy-aws']

jobs:
  # continuous-integration:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Step 1
  #     - uses: actions/checkout@v2

  continuous-deployment:
    runs-on: ubuntu-latest
    # needs: [continuous-integration]
    # if: github.ref == 'refs/heads/main'
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name application-name \
            --deployment-group-name AppDeploymentGroupName \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
